### ISSUE TITLE
Body does not unlock on Edge/IE11

### ISSUE THREAD

**Issue by erwstout** [ghosh/micromodal#101]
It appears that when using body locking to disable scroll, when the modal is closed it does not unlock. I took a look at the source code and it appears that the library is using `Object.assign` for this functionality. I added a polyfill for Object.assign to see if that solved it, but it does not. I'll try to dive in more when I get a chance and create a PR if possible - but if anyone has any suggestions or thoughts that would be great. Thanks!

**Comment by erwstout** [comment]
Addressed this with PR #102

**Comment by ghosh** [comment]
Merged PR. Thanks.
