### ISSUE TITLE
Modal opened by trigger cannot be closed by function close().

### ISSUE THREAD

**Issue by biglobe** [ghosh/micromodal#107]
From what i can understand so far, any modal opened by trigger cannot be closed by javascript function close().

One of the problem is... as specified in https://micromodal.now.sh, function close(id) is available, however in the codes, close function does not take in any parameter. Instead it closes whichever modal is in variable activeModal.

The underlying issue is that activeModal is not set when the modal is opened using the trigger **data-micromodal-trigger="modal-1"**. It is only triggered when modal is opened by calling show().

**Comment by Grabes** [comment]
Created pull request #108 that resolves the issue with activeModal not being set when modal us opened using the trigger.

**Comment by ghosh** [comment]
Fixed in #113
