### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by ytmagalhaes** [ghosh/micromodal#110]
Hi there!

Our company is using micromodal for popups and we are using `Vue + TypeScript` so it would be nice if we could get some `@types` added for better TypeScript support as right now we get a bunch of errors from our IDEs. It's worth noting it works fine, it's just the IDE doesn't know what to do with it.

Getting them added to [DefinitelyTyped](http://definitelytyped.org/) would give the plugin more visibility too.

**Comment by wcarson** [comment]
I took a shot at the type definitions. Follow the progress here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32693

**Comment by wcarson** [comment]
The type definitions are now available via NPM (@types/micromodal)

https://www.npmjs.com/package/@types/micromodal

This one can probably be closed.

**Comment by ytmagalhaes** [comment]
Thank you so much! That was so cool! We're definitely installing this as soon as we can and using it! Closing the PR 😄
