### ISSUE TITLE
MicroModal.close() does not accept an ID selector

### ISSUE THREAD

**Issue by roebuk** [ghosh/micromodal#112]
Hi,

Within the documentation `MicroModal.close` is documented that it takes a string for the ID of the modal is should perform the close on. Yet, within the code, the `close` function disregards this argument and calls `activeModal.closeModal();`

Would be is possible to allow `MicroModal.close` to accept an ID selector and close the modal where the ID matches?

**Comment by donbot-inc** [comment]
Reference #133

**Comment by ghosh** [comment]
Fixed in #113
