### ISSUE TITLE
Minifier is deprecated

### ISSUE THREAD

**Issue by kakadiadarpan** [ghosh/Micromodal#114]
Let's stop using [minifier](https://github.com/fizker/minifier) as it is deprecated. We should be able to replace this using uglify.

**Comment by kalpeshsingh** [comment]
I will take a look. Thanks Sir.

**Comment by kakadiadarpan** [comment]
I can help if you want 😄

**Comment by ghosh** [comment]
Has been replaced with terser. Closing this.
