### ISSUE TITLE
Enabling scrollBehaviour should remove inline styles

### ISSUE THREAD

**Issue by MatTheCat** [ghosh/micromodal#117]
[Line 91](https://github.com/ghosh/micromodal/blob/master/src/index.js#L91)

```javascript
Object.assign(body.style, {overflow: 'initial', height: 'initial'})
```

means any height/overflow set by CSS is overriden when a modal configured with `disableScroll` closes. Why not removing these by setting them to an empty string?

**Comment by ghosh** [comment]
Thanks for the suggestion. Fixed in latest release.
