### ISSUE TITLE
A project with Micromodal

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [ghosh/micromodal#118]
Hi guys,
Thanks for this awesome library!

I just want to tell you I'm using Micromodal on my recent released project (Popup Notices for WooCommerce):
https://wordpress.org/plugins/popup-notices-for-woocommerce/

It's a plugin for WooCommerce that replaces notices by modals.
I don't know if you are familiar with WordPress but anyway thanks!

I added Micromodal credits there.
I hope my project can help someone here too :)

See you

**Comment by ghosh** [comment]
Hi @pablo-sg-pacheco Thanks for letting us know. Wishing you all the best.
