### ISSUE TITLE
Original event is not available for onShow and onClose

### ISSUE THREAD

**Issue by pomartel** [ghosh/Micromodal#130]
The original event that triggers the opening and closing of the modal is not passed to the `onShow` or `onClose` function. This is useful information for my project (ie. need to read a data-attribute on the link that opened the modal) so I added the functionality to my repo in this commit: https://github.com/pomartel/micromodal/commit/daf4a43568c08c7fce3d7f8cd2bd0a62bdc556cf

I can bundle this in a clean pull request if it can be useful to others.

**Comment by MahbbRah** [comment]
YES YES, I'm in badly needs of this feature :( 
I tried your updated codes didn't work. can you do readme so we can use that?

**Comment by Antimated** [comment]
Very much in need of this

**Comment by ghosh** [comment]
@pomartel Would you be open to submitting a PR?

**Comment by pomartel** [comment]
Sure @ghosh , I'll have a look at it next week!

**Comment by sashahohloma** [comment]
I think, i found solution by using other method - `show(id, options)`
You can use this method with you custom data-attribute, also you need add eventlister for this elements.
Check my ES2015 compatible example:

```
var modalCustomSelector = 'data-custom-selector';

document.querySelectorAll('[' + modalCustomSelector + ']').forEach( (element) => {
    element.addEventListener('click', (event) => {

        event.preventDefault();
        var modalCustomId = event.target.closest('[' + modalCustomSelector + ']').getAttribute(modalCustomSelector);
        
        MicroModal.show(modalCustomId, {
            disableScroll: true,
            awaitCloseAnimation: true
        });

    });
});
```

If MicroModal was called this way, you can use `MicroModal.close('data-custom-selector')`

**Comment by pjoulot** [comment]
I have found this issue because I was reading the documentation.

I have been through the code and it has been fixed already, but the documentation has not been updated :(

There is a pull request.  #258

**Comment by ghosh** [comment]
Thanks @pjoulot. Seems like I missed this.

**Comment by jmosbech** [comment]
@ghosh and @pjoulot The npm version and the code in master does not seem to have these changes. Am I missing something?

**Comment by ghosh** [comment]
@jmosbech This is scheduled for the next release. This should not have been closed before.

**Comment by DmytroLitvinov** [comment]
Hi @ghosh ,

Thanks a lot of reporting :)
Could we be aware when new release with passing event will released?

**Comment by ghosh** [comment]
@DmytroLitvinov It should be released in a few weeks.

**Comment by ghosh** [comment]
Fixed in `0.4.3`

**Comment by DmytroLitvinov** [comment]
Thanks for release :)
Maybe it would also good to track release on GitHub?

**Comment by ghosh** [comment]
Yes planing on doing that. I'm trying to setup github actions for release. Should be able to track releases on GH soon.
