### ISSUE TITLE
development question [NOT AN ISSUE]

### ISSUE THREAD

**Issue by gautamz07** [ghosh/micromodal#131]
Hey guys , while developing the plugin , do you guys directly import the index.js file from the src directory and work on it in the latest chrome ? i believe, if your developing a plugin , you want to see how your source code work instead of your compiled code , so how do you go about having the index.js written in ES6 work in any modern browser ? 

Any insights on this would be highly appreciated. 

Thank you.

**Comment by ghosh** [comment]
This library is used is a lot of contexts in different browsers and versions. Since our users are not using only modern browsers, it does not make sense for use to focus on running es6 in the browsers yet.

Cheers!
