### ISSUE TITLE
Prevent user from closing modal

### ISSUE THREAD

**Issue by bradley-varol** [ghosh/micromodal#132]
I'd like to temporarily prevent the user from closing the modal by clicking the overlay. Is this possible?

Also, is there a way for me to open a modal while a previous modal is already open and have the previous one close? I tried to loop through all but the current `.modal.is-open` elements and `.close()` them from inside the `openTrigger` callback but wasn't successful:
```
onShow: function (modal) {
    let openModals = document.querySelectorAll('.modal.is-open');
    const openModalsCount = openModals.length;
    for (let i = 0; i < openModalsCount; i++) {
        if (openModals[i].id === modal.id) {
            return;
        }
        MicroModal.close(modal.id);
    }
}
```
`Cannot read property 'closeModal' of null`

Thanks :)

**Comment by slowernet** [comment]
Per #176, this can be done by removing the `data-micromodal-close` attribute from the overlay element.

**Comment by kakadiadarpan** [comment]
Thanks for the help @slowernet! 

@bradley-varol Please refer to this [comment](https://github.com/ghosh/micromodal/issues/176#issuecomment-472785589) on #176

>data-micromodal-close is a special attribute which indicates that the element that it is on should trigger the close of the modal on click. If we remove that attribute (from the overlay element), clicking on the overlay will not close the modal anymore.

Please reopen this issue if you need more help

**Comment by bradley-varol** [comment]
Much appreciated guys 👍
