### ISSUE TITLE
disableScroll: true on mobile still scrolls the body.

### ISSUE THREAD

**Issue by ukutaht** [ghosh/micromodal#138]
First of all, thank you for a great library!

I'm running into an issue with disableScroll on mobile. It seems to have no effect only on my iPhone 8. Works perfectly on desktop and on Chrome devtools iphone simulator. Haven't tried with the xcode simulator yet.

![ezgif-3-a92a170d128b](https://user-images.githubusercontent.com/3731516/48278486-934d6780-e445-11e8-8ec6-21810ee479c5.gif)

The same modal disables scroll behaviour perfectly on desktop. I'm using micromodal through NPM:  `"micromodal": "^0.3.2"`.

Any ideas what could be going wrong here?

**Comment by klickreflex** [comment]
I ran into the same problem and got it solved by using a package called [scroll-lock](https://github.com/FL3NKEY/scroll-lock), maybe this helps people coming here.

I simply call it in MicroModals `onShow` and `onClose` listeners:

```js
import { disablePageScroll, enablePageScroll } from 'scroll-lock';

MicroModal.init({
    onShow: modal => disablePageScroll(modal),
    onClose: modal => enablePageScroll(modal),
});
```

It si supposed to automatically make children of the scrollable item scrollable, too. However, this didn't work in my use-case, but I got around by explicitly setting the data attribute `data-scroll-lock-scrollable` on any item inside my modal that required scrolling.
