### ISSUE TITLE
Could be a node instead of a string of an id

### ISSUE THREAD

**Issue by kud** [ghosh/Micromodal#139]
https://github.com/ghosh/micromodal/blob/bc03d6d972caf11dccff557eadcd00b7ab75b2f3/src/index.js#L34

**Comment by ghosh** [comment]
@kud, I do not understand what you mean. Could you explain it in more detail?

**Comment by kud** [comment]
Hey @ghosh , sorry, it's not well explained.

There, `this.modal = document.getElementById(targetModal)` you're asking for `targetModal` as a string of an id.

I would like to be able to give a node instead of a string of an idea, like

`document.querySelector("my-selector")`

It allows the user to give anything they want as node, instead of necessarly an id.

**Comment by ghosh** [comment]
hmm..ok fair point. Will consider this. Thanks for opening an issue.

**Comment by kud** [comment]
No worries, thank you so much :)

Most of libs give the possibilty to enter either an id either a DOMNode. It's useful for beginners and advanced developers IMO.

**Comment by kud** [comment]
`this.modal = typeof targetModal === "string" ? document.getElementById(targetModal) : targetModal`

**Comment by ghosh** [comment]
Duplicate of #65
