### ISSUE TITLE
Single modal is allowed

### ISSUE THREAD

**Issue by doanguyen** [ghosh/micromodal#166]
Hello,

I just have a small question regarding a specific case, I wanted to implement only one modal at a time, if other modal is triggered, the current modal is close make way for the new modal.
Do you have recommend on how to implement this?

Thank you.

**Comment by ghosh** [comment]
Sorry, we do not support this right now. A question to you - in which scenario would you want to do something like this? Typically, clicking on anything apart from the modal, when the modal is open should cause it close.

**Comment by doanguyen** [comment]
Thanks for the reply,

I had come up with the same solution, just for travellers who have the same interest, what I've done is adding these 4 line on top of showModal method in Modal class:

`var opened = document.querySelectorAll('.m,odal.modal-slide.is-open');
opened.forEach(function(element){
    element.classList.remove('is-open');
});
`

Anyway, thanks for a great library.
