### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [ghosh/micromodal#167]
Hi, what is the current status of this project? Is it still maintained?

**Comment by ghosh** [comment]
We intent on maintaining this. Was burnt out for a most part of last year. Working on closing out these issues soon.

**Comment by DanielRuf** [comment]
Ok thanks for the info and no rush. Just wanted to know if there will be updates in the future. And I often also recommend moving such big (number of stars and downloads) to an org account and add a few more maintainers.

**Comment by DanielRuf** [comment]
Ok thanks for the info and no rush. Just wanted to know if there will be updates in the future. And I often also recommend moving such big projects (number of stars and downloads) to an org account and add a few more maintainers.

**Comment by ghosh** [comment]
Agree. Will probably do that.
