### ISSUE TITLE
fail to install yarn packages with node 10.x

### ISSUE THREAD

**Issue by rubenslopes** [ghosh/micromodal#168]
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.15.0"

any change to upath be bumped or something like that?

in the meantime all rollback my nodejs

**Comment by ghosh** [comment]
Yup, working on a fix. Should be fixed in next release.

**Comment by ghosh** [comment]
Was a problem of outdated dependencies. Fixed now.
