### ISSUE TITLE
Missing `img` on README.md

### ISSUE THREAD

**Issue by paschalidi** [ghosh/micromodal#177]
Loving the lib and the simplicity! 

This is not a crucial issue but if I was you, who is getting lots of attention at the moment with this library I would pay attention to this detail.

The first image of the README.md 
```
<img src="https://www.dropbox.com/s/dhi0o4hfn3n8vtc/logo.svg?raw=1" width="100px"/>
```
is missing.

Let me know how I can help you with that and I would be glad to do so.

**Comment by ghosh** [comment]
HI thanks for the heads up. Its been fixed.
