### ISSUE TITLE
Correct focus on modal opening

### ISSUE THREAD

**Issue by OwenMelbz** [ghosh/Micromodal#180]
Hi,

Liking the package, however when running it through an accessibility audit, several points came up.

E.g. the problem described https://alphagov.github.io/accessibility-tool-audit/test-cases.html#content-first-instance-of-abbreviation-not-expanded under the "lightbox" section.

When opening a modal, the focus should almost immediately change to the new context so that a screen reader can announce and start reading.

Currently when the modal opens it focuses on the close button - giving visually impaired users no helpful visibility of the content.

Instead you should make sure either the title of the modal or the modal content is automatically focused, you can even utilise `aria-live` to help presenting the user with the new content immediately.

Thanks :D

**Comment by toastal** [comment]
Correct me if I'm wrong but, I think it should skip the `data-micromodal-close` when finding the first focusable element, and if one is not found, then feel free to select the close button so the user can press enter to close.
