### ISSUE TITLE
Issues when I close opened window

### ISSUE THREAD

**Issue by jukuan** [ghosh/Micromodal#182]
Hi,

Thanks for your library. I'd like to tell about the issues I faced by:

1) It's not worked when a modal window on the page is opened by default (before JS).
The window does not close when I'm trying to close a window opened manually. As hotfix, I have to invoke `this.open()` method before `this.close()`, but it's strange because the window is opened already. Could you please add an 'init' method?

2) I cannot close specified modal when I have multiple windows opened.
If I have on page 2 or more modal windows I cannot invoke .close() method for one of them. I have to call `.open()` method (again!) and only after the closing works.

I believe, adding an 'init' method will help me (and my colleges) with my issues and I can make your library more flexible and popular. Thanks.

**Comment by kakadiadarpan** [comment]
Hi @jukuan, could you please provide a minimal reproduction of this issue?

**Comment by cojaco** [comment]
I think, I have the same problem.
To illustrate the problem, I forked a fine working example on Codepen.
The original: https://codepen.io/scalblog/pen/ERzzVE
my Fork: https://codepen.io/cojaco/pen/qGGWJr
here I simply add the class is-open, and set aria-hidden="false".

Now the modal is open on page entry but it can't be closed.

**Comment by ghosh** [comment]
Unfortunately, there is no way for the modal to know that a modal is already open on page load. What you are trying cannot be achieved with this library.

In an effort to keep the bundle size small, we will not be supporting this feature. There are many other modal libraries which would help you out with this. 

Thanks for trying out Micromodal.
