### ISSUE TITLE
onShow and onClose not triggering when showing modal programmatically

### ISSUE THREAD

**Issue by Antimated** [ghosh/Micromodal#187]
Whenever you show a modal programmaticaly with `MicroModal.show('modal-id');` you are not able to use the onShow and onClose methods as they don't trigger.
This only happens if you don't provide a `data-micromodal-trigger` element (which in this case I don't need). Any way to bypass this problem?

**Comment by ghosh** [comment]
Thanks for opening an issue. Fixed in #113

**Comment by besimhu** [comment]
@ghosh this is broken in the latest version I tested. The `onShow` and `onClose` do not register.

**Comment by glenpike** [comment]
> @ghosh this is broken in the latest version I tested. The `onShow` and `onClose` do not register. You also can't close a modal with the close button when opened programmatically.
Workaround here is to pass in the config to MicroModal.show, e.g.

```
  function onShow(modal) {
    console.info(`${modal.id} is shown`)
  }
  function onClose(modal) {
    console.info(`${modal.id} is hidden`)
  }
  MicroModal.init();
  MicroModal.show('maintenance-modal', {
    onShow: onShow
    onClose: onClose
  });
```

**Comment by elliottregan** [comment]
Yea, this is still broken in the latest version 0.4.2.

**Comment by simplenotezy** [comment]
I believe this functionality is broken as well :/

**Comment by besimhu** [comment]
@simplenotezy  I switched to https://github.com/edenspiekermann/a11y-dialog and I need a working modal.

**Comment by simplenotezy** [comment]
@besimhu thanks. That looks lightweight as well. I figured I could just use my CSS frameworks modal (Bulma)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NikitaChernykh** [comment]
I tested it today and it is still broken v0.4.6

**Comment by neeeilpatrick** [comment]
Yep. It's still broken.  

I needed to use MicroModal.show() so I just did this as a work around with the issue.

```
let modal_id = 'location-form'
let target = document.getElementById(modal_id)
let config = {attributes: true}

let observer = new MutationObserver((mutationList)=>{
    for(let mutation of mutationList){
        if(mutation.type=='attributes' && mutation.attributeName=='aria-hidden'){
            if(mutation.target.ariaHidden){
                // IF MODAL CLOSES
            }else {
                // IF MODAL SHOWS
            }
        }
    }
})

observer.observe(target, config)
````

**Comment by Antimated** [comment]
As of today still broken, came looking for a solution online just to find my own question here lol.

**Comment by Poselsky** [comment]
https://github.com/ghosh/Micromodal/blob/4d03e7ee5265a749f079922f3c6855c1da80765a/lib/src/index.js#L305

Saw this line. If you won't pass config into show and close method, config won't be used at all.

```javascript
const options = config || {}
```

If init function would save global config for each modal id, tracing configs would be a lot easier.

**Comment by AwakenTheJaken** [comment]
@ghosh Hope you are well, this still seems to be an issue, can we re-open this?

**Comment by Apu889** [comment]
i've been trying to figured out this for literally 1 week... still no luck :( 
this library is the most easy to use & versatile comparing others in the internet. this is very unfortunate.
