### ISSUE TITLE
prevent default event of open trigger event

### ISSUE THREAD

**Issue by zebapy** [ghosh/Micromodal#189]
I have a modal and my open trigger is an link `a[data-micrmodal-trigger]` 

It's a link so the no-js fallback can be a link to a normal page. The problem is micromodal does not seem to prevent the default action of the trigger so the modal opens then the page changes. 

Any reason not to do `event.preventDefault()` on the open trigger?

**Comment by ghosh** [comment]
@zebapy Fair point. Can't think of a scenario where `event.preventDefault()` would adversely effect the use case. Would be open to submitting a PR? 

@kalpeshsingh Any thoughts on this?

**Comment by zebapy** [comment]
Looks like @gautamz07 opened one

**Comment by zebapy** [comment]
@ghosh I thought this was merged but I still have the same problem with 0.4.0. Here's reproduction https://codesandbox.io/s/micromodal-bug-wnibs

**Comment by ghosh** [comment]
@zebapy, yes its merged but not yet released. Working on some other things to release with this.

**Comment by ghosh** [comment]
Fixed in `0.4.3`

**Comment by mattobee** [comment]
@ghosh This doesn't seem to be working in v0.4.6. Was the fix rolled back at some point?

**Comment by daltonrooney** [comment]
Try 
```
MicroModal.init({
    onShow: function(modal, element, event) {
        event.preventDefault();
        event.stopPropagation();
    }
});
```
