### ISSUE TITLE
Problems when trying to open/close programmatically

### ISSUE THREAD

**Issue by kbudasov** [ghosh/Micromodal#196]
When having only modal ID (without element with `data-trigger-attrribute`), modal callback doesn't work
(triggered `MicroModal.show('modal-id'); // [1]`)
Also, unable to close modal by triggering
`MicroModal.close('modal-id'); // [2]`

**Comment by kbudasov** [comment]
To clarify the situation: yes, I can use "custom" callbacks; but still unable to extend standard config (provided in Global Init function)

**Comment by mrmathewc** [comment]
Also had issues with this. A workaround was I added an ID to the close trigger, then just executed `$('#modal-close').click();` where necessary, in my case was on Ajax success.

**Comment by ghosh** [comment]
Closing as duplicate of #197. Will be fixed in next release.

**Comment by cnobile2012** [comment]
I'm having the same close issue. I haven't tried the issue with a callback.
