### ISSUE TITLE
What a dumb piece of shit...

### ISSUE THREAD

**Issue by vacoup95** [ghosh/Micromodal#209]
Really there's nothing you can do with this piece of garbage. I thought there was supposed to be a fucking way (by default) to pass a parameter. But either, you didn't document that or it is not possible. So in other words, I wasted 2 hours trying to make this garbage work properly. 

My issue: why can't I simply create a modal, pass an ID to it when it's opened. And when you click a button execute a function with that variable inside?

**Comment by leeoniya** [comment]
you definitely deserve a full refund...oh wait.

**Comment by vacoup95** [comment]
yeah... refund my time. or at least say on the page in <h1> that this library cannot do anything usefull..

**Comment by ghosh** [comment]
@vacoup95 I can understand that this might have been an inconvenience to you.

However, please realise that we maintain this library in our free time and it is not possible to have every feature available out of the box.

Opening an issue and requesting a feature is enough to get it considered for a future release.

Please be kind and have some respect for OSS maker’s and maintainer’s time and effort.
