### ISSUE TITLE
Some feeedback

### ISSUE THREAD

**Issue by svinkle** [ghosh/micromodal#21]
Hello! I was [asked via Twitter](https://twitter.com/knowkalpesh/status/917776174830555136) for feedback on the modal here, so here we go.

A few things stick out to me, mostly low to medium severity. For the majority, the expected functionality and accessible experience is all there, so kudos for that! I also really like how things have been documented with HTML comments then corresponding numbered bullets below; very easy to read and follow.

A few things I'd recommend:

1. Remove `aria-describedby` as this will announce the entirety of the modal content upon launch. It's just a lot of content to take in and could overwhelm some people with too much info all at once. Imagine if there was a modal for something like a privacy policy or terms of use…

2. Remove [`role="document"`](https://www.w3.org/TR/wai-aria/roles#document) as this is the default role and is not required to be specified. Will also result in one less required `div`!

3. Recommend to change the `h3` to an `h2` as often modal content represents a major section within the page. It's a much safer heading level to use as there _should_ be an `h1` present above in the current document, then the `h2` for the next major section. `h3` assumes a preceding `h2` and that can't really be guaranteed.

4. I've never seen [`aria-controls`](https://www.w3.org/TR/wai-aria-1.1/#aria-controls) used in this manner before. I guess technically it's ok, but not required.

5. I suppose I see the reason for the `role="document"` now that I spot the use of `header` and `main` elements. I'd recommend not having these as well, especially the `main` as there _should_ only be one and it's likely already in use in the document below the modal window.

6. People can still get to the content "below" the modal window using other means such as the VoiceOver cursor (`Ctrl` + `Opt` + `right` or `left` arrows) which is not ideal. To get around this, I recommend using the `inert` attribute. This is something new that doesn't exist yet in browsers, so here's the [inert polyfill](https://github.com/WICG/inert) and related [video explaining the `inert` polyfill](https://www.youtube.com/watch?v=fGLp_gfMMGU) it in more detail.

Again, these are minor nit-pick type things, but worth looking into and considering. Either way, nice work! 👍

**Comment by ghosh** [comment]
@svinkle Thanks a ton for leaving this here. Really appreciate you taking the time to leave such a detailed feedback.

We will work on it and make the changes as required. 

Cheers 👍

**Comment by kalpeshsingh** [comment]
Hello Scott,

Thanks for leaving such detailed feedback. We appreciate your time to dig into entire code and come up with good suggestions.

Unfortunately, I failed to find `role=document` as default role in the link you mentioned. Could you please point to more specific doc. Also, seems like [`aria-controls`](http://www.heydonworks.com/article/aria-controls-is-poop) doesn't hold much value. 

We have added this issue in our next major milestone and will keep you updated. 👍

**Comment by svinkle** [comment]
Hi @kalpeshsingh,

When I mentioned `role=document` I was referring to the fact that the default role of the browser itself is "document." I see in your description for including this role states:
>It helps inform screen-readers and other assistive technologies about a separate document context within the modal.

I don't believe this to be true, as the modal context remains as part of the original document which launched the modal window. For example, if JavaScript weren't available for some reason to launch the modal, the content within the modal window will simply appear as part of the underlying content document, correct?

A container with `role=dialog` is essentially presenting a new context of, "this portion of content is important, please pay attention to this before moving on." This is why I suggest that this role and `div` is not required.

I agree, `aria-controls` doesn't present much value here either.

Please refer to the [WAI-ARIA Authoring Practices 1.1 - Dialog documentation](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal) on which attributes are required.

**Comment by kalpeshsingh** [comment]
Thanks Scott. 
Your points make sense. We will work on them.
