### ISSUE TITLE
disableScroll: true changing scroll position

### ISSUE THREAD

**Issue by Newbrict** [ghosh/Micromodal#224]
Hi - Great project!

One issue I am seeing on my page [sensor.fyi](https://sensor.fyi/mice) is when I open any modals with the `disableScroll` set to true it will change the scroll position while the modal is open. Modals on this page are opened by clicking the 
![image](https://user-images.githubusercontent.com/1683041/62304648-6403de00-b44c-11e9-966d-28764c879b98.png)
icons

This is normally not a big deal since it will scroll back to the original position, UNLESS you are at the bottom of the page in which case it just scrolls you up and leaves you there. This can be tested by clicking this particular icon.

![image](https://user-images.githubusercontent.com/1683041/62304596-49ca0000-b44c-11e9-9eff-e75e976af0f4.png)

Is this normal behavior that `disableScroll` actually causes the page to scroll?

**Comment by daltonrooney** [comment]
I was having this problem as well. Adding `overflow: hidden !important;` to the HTML tag when the modal is active fixed it for me.

**Comment by Adoonq** [comment]
![image](https://user-images.githubusercontent.com/18928419/65379929-4844e780-dcd9-11e9-8ed8-29177d2e96c0.png)
This is due to centering and fixed height.
`body {justify-content: flex-start} `

**Comment by ghosh** [comment]
Fixed in `0.4.3`
