### ISSUE TITLE
Enabled scroll when nested modal is closed

### ISSUE THREAD

**Issue by julmot** [ghosh/Micromodal#232]
When closing a second level modal, the scroll is enabled (`disableScroll`) again, even though a first level modal still exists. There must be a check whether another modal exists before enabling it. Otherwise it won't support nested modals.

**Comment by ghosh** [comment]
@julmot Appreciate you opening this PR.

However, in the interest of keeping this library lightweight and simple, we would not be adding support for nested modals. If over time demand for this feature grows, we could consider this again.

**Comment by doMynation** [comment]
I'd also be interested in this, should you decide to re-open the issue. Thank you.
