### ISSUE TITLE
Closing a nested modal will also close the other

### ISSUE THREAD

**Issue by julmot** [ghosh/Micromodal#233]
Imagine the following situation:

Two modals, one above the other. Let's call the modal that overlapps the other modal A, and the overlapped modal B.

When closing modal B programmatically using `microModal.close('the-id')`, then this will not only close modal B, but also modal A. After digging into the code a  little bit I think the reason is that the plugin stores an instance of "activeModal", which in this case will be a reference to modal A (since modal A will be opened after modal B). This explains why it also closes modal A, not only B.

The workaround so far for me is to trigger a click on the micromodal close button, because this button will hold the correct instance. Only if this doesn't work, I will call the official API method.

```javascript
    if (this.closeButton) {
      this.closeButton.click();
    } else {
      microModal.close(this.modalId, {
        awaitCloseAnimation: true
      });
    }
```

To solve this once and for all, please make the class `Modal` exportable directly, so it's possible to interact with multiple instances (avoid any kind of `activeModal`).

**Comment by ghosh** [comment]
@julmot Appreciate you opening this PR.

However, in the interest of keeping this library lightweight and simple, we would not be adding support for nested modals. If over time demand for this feature grows, we could consider this again.

**Comment by stepanO** [comment]
it's not a feature, it's bug in the code, because when closing first modal the lib looks worked correctly, but it's not.

At least please add message to ReadMe about is not support nested modals.

I really frustrated because I have a lot of modals on Prod, but I need have just 1 modal which could open nested modal.
