### ISSUE TITLE
CDN is offline

### ISSUE THREAD

**Issue by coenvc** [ghosh/Micromodal#242]
We are using the CDN for multiple projects but it is currently offline

**Comment by kakadiadarpan** [comment]
@coenvc Which CDN link are you using?

**Comment by coenvc** [comment]
Hey @kakadiadarpan i'm using this one: https://unpkg.com/micromodal@0.4.1/dist/micromodal.min.js

**Comment by nc-jhof** [comment]
We are also badly affected by this. When can we get this url up again?

**Comment by kakadiadarpan** [comment]
Can you guys switch to [JSDelivr](https://cdn.jsdelivr.net/npm/micromodal/dist/micromodal.min.js) for now?

It'll take us some time to get it back up.

**Comment by nc-jhof** [comment]
Our application requires a deploy package in order to change the url in the code and this can take up to a day. We are still badly blocked by this.

**Comment by ghosh** [comment]
Sorry for the outage guys, we are working on fixing this.

**Comment by ghosh** [comment]
The CDN link should be back up now. Here is the latest link available on unpkg - https://unpkg.com/micromodal@0.4.2/dist/micromodal.min.js

**Comment by nc-jhof** [comment]
@ghosh Can you also get 0.4.1 up as well?

**Comment by ghosh** [comment]
hmm... I'm not sure if that's possible. @kakadiadarpan Thoughts?

**Comment by kakadiadarpan** [comment]
@nc-jhof `unpkg` delivers everything from npm. So, it is not possible to publish the already published version. You'll have to update to `0.4.2`
