### ISSUE TITLE
Touchstart Event Circumventing Link Hover Behvaior on iOS 

### ISSUE THREAD

**Issue by douglas-johnson** [ghosh/Micromodal#248]
I am experiencing an issue in Safari on iOS 12.4.1 using an iPhone 8.

I have a menu where some items have a sub-menu. By default, the initial touch of a menu item with a sub-menu will trigger the hover state and show the sub-menu.

When I place that menu within a modal, the initial touch will follow the link immediately.

I found two options for fixing this, and I'm open to submitting a pull request if you approve of one of these methods.

### Option 1

Removing this touchstart event fixed it on my device. Everything else about the modal continued to work as expected.
https://github.com/ghosh/Micromodal/blob/master/lib/src/index.js#L117

### Option 2

Instead of checking if the touched or clicked element has the closeTrigger attribute during the event, only add the event listener to elements within the modal that have the closeTrigger attribute.

Remove this:
https://github.com/ghosh/Micromodal/blob/master/lib/src/index.js#L129

Update addEventListeners and removeEventListeners with something like getCloseTriggers() that returns an array of elements where the event listeners should be added or removed.

**Comment by ghosh** [comment]
Should be fixed by #479
