### ISSUE TITLE
Doesn't work with templates

### ISSUE THREAD

**Issue by IryArkhy** [ghosh/Micromodal#253]
I'm using Handlebars in my project to add dynamic content on a page. Unfortunately triggering a micromodal in a template doesn't work. Method **MicroModal.show("id")** does not work either.

Template (passed js-micromodal-trigger="modal-two"  as an attribute):

At the picture
<img width="991" alt="Снимок экрана 2019-10-04 в 12 20 09" src="https://user-images.githubusercontent.com/46995636/66196519-5e6f8200-e6a1-11e9-9170-4be626ce2965.png">

Config:
`MicroModal.init({
    onShow: modal => console.info(`${modal.id} is shown`), 
    onClose: modal => console.info(`${modal.id} is hidden`), 
    openTrigger: 'js-micromodal-trigger',
    closeTrigger: 'js-micromodal-close',
});`

P.S. If a button(link) is hardcoded and does not belong to dynamic elements then Micromodal works fine.

Do you have any solution for this particular situation? Thank you.

**Comment by ghosh** [comment]
@IryArkhy Thanks for opening this issue. Micromodal attaches events to all target at the time of initialization, there is no way for it know that new content has been added to the page and therefore it does not bind events to the new elements.

At this moment, I'm afraid this functionality is not available.
