### ISSUE TITLE
GulpUglifyError: unable to minify JavaScript

### ISSUE THREAD

**Issue by ihsan-ofluoglu** [ghosh/Micromodal#255]
micromodal Version 0.4.2
gulp-uglify Version 3.0.2

my package.json
![Screenshot 2019-10-16 at 14 03 15](https://user-images.githubusercontent.com/46676742/66913640-bdc47f00-f01d-11e9-8c46-9b66376c29fb.png)

![Screenshot 2019-10-16 at 14 01 16](https://user-images.githubusercontent.com/46676742/66913544-848c0f00-f01d-11e9-866b-1ce08bef1577.png)

Error:
![Screenshot 2019-10-16 at 14 06 23](https://user-images.githubusercontent.com/46676742/66913859-37f50380-f01e-11e9-912f-445532f88ba5.png)

**Comment by ghosh** [comment]
We now use terser with rollup to minify the code. Closing as outdated.

**Comment by TidyLuke** [comment]
Hello @ihsan-ofluoglu & @ghosh , I'm currently seeing this issue now. Commenting out the import my process works, but not when MicroModel is imported. Did you manage to fix this @ihsan-ofluoglu ?
