### ISSUE TITLE
Question about showModal/onShow parameters

### ISSUE THREAD

**Issue by netfalo** [ghosh/Micromodal#259]
Hi,

Is the click event intentionally not used in the showModal?

In the registerTriggers it is passed in, but it is not used in the showModal
registerTriggers:
`trigger.addEventListener('click', event => this.showModal(event))`
showModal:
`showModal () {`

It would be useful to know the triggering click event in the config.onShow.

In my usecase I need to modify the modal content during onShow.

BR
/Marci

**Comment by ghosh** [comment]
Duplicate of #130
