### ISSUE TITLE
Make "setFocusToFirstNode" optional

### ISSUE THREAD

**Issue by ataylor32** [ghosh/micromodal#26]
I have a modal with a form and opening the modal is not a good experience on iPhones due to the first focusable node being focused automatically.

In portrait mode, you can see that a field has focus, but you can't see that the label of the field is "First name":

![portrait](https://user-images.githubusercontent.com/1054222/31502766-3716b160-af2b-11e7-9070-e88f69edd50c.png)

In landscape mode, you can't see that a field has focus:

![landscape](https://user-images.githubusercontent.com/1054222/31502800-4d7c25ca-af2b-11e7-971e-76e530716d3e.png)

It would be nice if `setFocusToFirstNode` was optional.

**Comment by kalpeshsingh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make "setFocusToFirstNode" optional](https://trello.com/c/QrfaxPRe/44-make-setfocustofirstnode-optional)

**Comment by ghosh** [comment]
@ataylor32 Thanks for reporting this. Will do.
