### ISSUE TITLE
Add overscroll-behavior: contain to modal content

### ISSUE THREAD

**Issue by jq-87** [ghosh/Micromodal#286]
This will prevent the underlying page content from scrolling when the modal content scroll has reached the end.

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

The w3.org example does not use `overscroll-behavior` but the underlying page content does not scroll when the modal is active:
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

Using `overscroll-behavior` is nicer in my opinion because it prevents scroll chaining while visitors are scrolling the modal content; BUT still lets visitors scroll the underlying page content if scroll is initiated outside of the modal body.

**Comment by ghosh** [comment]
This ability already exists, see the `disableScroll` setting in configuration here - https://micromodal.now.sh/#configuration
