### ISSUE TITLE
Pause or Stop YouTube Video on Modal Close

### ISSUE THREAD

**Issue by twd3** [ghosh/Micromodal#298]
I'm having a really hard time getting this done. Can you point me in the right direction?

**Comment by kakadiadarpan** [comment]
You can do that by defining what to do in the `onClose` handler. Check the documentation here: https://micromodal.now.sh/#configuration

**Comment by twd3** [comment]
If anyone needs to stop videos from playing on modal close:
```
MicroModal.init({
  onClose: modal => {
      modal.querySelectorAll('.d3-youtube-iframe').forEach(iframe => {
          iframe.setAttribute('src', iframe.getAttribute('src'));
      });
  },
});
```
