### ISSUE TITLE
Cannot focus / edit textfields

### ISSUE THREAD

**Issue by rjewell808** [ghosh/Micromodal#299]
I cannot get any type of textfields / textareas to work inside the modals. More specifically it seems I cannot focus into the fields such as by clicking on it.

Here's the code I'm trying it with:
```
<div class="micro-modal micromodal-slide" id="test-modal" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true">
      <div class="modal__content">
      	<input placeholder="test" type="text">
      </div>
    </div>
  </div>
</div>
```

I tested it with other inputs such as checkboxes and those work fine.

**Comment by ghosh** [comment]
Seems to work fine for me. Also there is an instance of a modal with a from on the homepage. Click the `trigger modal` link to see it action.

Closing this for now. Feel free to open if there is any issue.

**Comment by saosangmo** [comment]
I get the same error, I can not type text on input field and choose one option from select field.
