### ISSUE TITLE
disableScroll not working on iOS 12

### ISSUE THREAD

**Issue by jq-87** [ghosh/Micromodal#307]
iOS version: 12
Mobile Safari version: 12

Doing the following works in macOS (Mojave) Safari 13 but not iOS mobile Safari 12.

Body still scrolls:
```
MicroModal.show( 'my-modal', {
  disableScroll: true
});
````

**Comment by ghosh** [comment]
Thanks for reporting @jq-87. Will investigate.

**Comment by ghosh** [comment]
Should be fixed with #395
