### ISSUE TITLE
Got TypeError: Cannot read property 'focus' of undefined after v0.4.5

### ISSUE THREAD

**Issue by cron13** [ghosh/Micromodal#308]
Good day, after upgrade to 0.4.5 i got error ```TypeError: Cannot read property 'focus' of undefined
    at Modal.setFocusToFirstNode (micromodal.es.js?a1b7:259)
    at Modal.showModal (micromodal.es.js?a1b7:152)
    at Object.show (micromodal.es.js?a1b7:415)```

after modal showed

Thank you!

**Comment by ghosh** [comment]
@cron13 Can you please share your code? Specifically the modal.

**Comment by RettentoRectangle** [comment]
Same here:

TypeError: focusableNodes[0] is undefined
micromodal.es.js:259

**Comment by ghosh** [comment]
@RettentoRectangle Can you please share your modal code?

**Comment by RettentoRectangle** [comment]
Nothing special:

export default function Modal (props: IModalProps, appendable: HTMLElement): Promise<void> {
  ...

  MicroModal.show(id, {
    debugMode: __DEV__,
    awaitCloseAnimation: animation,
    onClose: (elem) => {
      ...
      resolve()
    })
})

--------------------

v0.4.6 works.
Thanks!
