### ISSUE TITLE
Can with fullscreen modal support?

### ISSUE THREAD

**Issue by suoc** [ghosh/Micromodal#326]
Will consider about this?

**Comment by kakadiadarpan** [comment]
@suoc What do you mean by full-screen modal?

**Comment by suoc** [comment]
> @suoc What do you mean by full-screen modal?
See [bootstrap-fullscreen-modal](https://github.com/benallfree/bootstrap-fullscreen-modal)

**Comment by ghosh** [comment]
@suoc It's highly unlikely we will implement this feature. 

If you are just looking for a solution where the modal covers the browser window, that can be achieved with css.

Closing this for now.
