### ISSUE TITLE
If MicroModal.show on load => data-custom-close not working

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [ghosh/Micromodal#350]
Demo:
https://codepen.io/ezra_siton/pen/vYLRYqO?editors=1100

Only if I close the modal (by ESC) - and open the modal again the `close` button works fine. 

Maybe related:
https://github.com/ghosh/Micromodal/issues/187

**Comment by chris-lawton** [comment]
It's this - https://github.com/ghosh/Micromodal/issues/385

> If a user uses the show method they assume that it will open the modal with the same config as they used to init the modal. This is not the case, all config settings from the original init are replaced when using the show method.

In your instance you need to add `closeTrigger` to `MicroModal.show`:

```
MicroModal.show('modal-1', {
    closeTrigger: 'data-custom-close',
});  
```

https://codepen.io/chrislawton/pen/yLVRzxL?editors=1000

**Comment by Ezra-Siton-UIX** [comment]
Thanks! this solves the issue. Anyway, it is **very hard** for users to notice this issue.
