### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by nlemoine** [ghosh/micromodal#36]
In [package.json](https://github.com/ghosh/micromodal/blob/523d23c678f36f9a699ecadb6a0aa7cbb31eddab/package.json#L5)

I think `main` should provide the non ES6 version of micromodal (`dist/micromodal.min.js`). I have some errors bundling it with browserify.

**Comment by ghosh** [comment]
@nlemoine Hey, I'm not sure if that would be possible as we have to maintain compatibility with ES6 as well.

You can use a babel transform with your Browserify. This should help you out - https://github.com/babel/babelify

Closing this for now, as ES6 imports already work. Feel free to let know if you face difficulties.

**Comment by nlemoine** [comment]
Thanks for your feedback.

I'm already using babelify (my project code is ES6) but I'm having the same issue described here: https://github.com/babel/babelify/issues/247
Maybe a babelify issue but I'm wondering how this can work as babelify presets aren't always the same across projects (using `global: true` results in a error saying `Couldn't find preset "latest"`). 

I think you can keep your original code in ES6 and provide multiple versions allowing developers to select the one depending on their environment. See: https://medium.com/@tarkus/how-to-build-and-publish-es6-modules-today-with-babel-and-rollup-4426d9c7ca71

Anyway, I fixed my issue for now using the dist version: `import micromodal from 'micromodal/dist/micromodal'`

**Comment by nlemoine** [comment]
@ghosh Please see: https://github.com/rollup/rollup-plugin-babel#external-dependencies

Would consider reopening the issue?

**Comment by ghosh** [comment]
@nlemoine Thanks for the update and the relevant documentation.

Will look into it.

**Comment by nlemoine** [comment]
Thanks for considering the request! 👍
