### ISSUE TITLE
forEach lacks browser support

### ISSUE THREAD

**Issue by BartdeBruin** [ghosh/micromodal#38]
The forEach gives an error in Edge and FF.

SCRIPT438: Object doesn't support property or method 'forEach'

**Comment by Semigradsky** [comment]
Yeah, demo is not working in Edge.

`NodeList` didn't have `foreach` method.

**Comment by nlemoine** [comment]
Just submitted a PR that resolves this issue.

**Comment by kalpeshsingh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [forEach lacks browser support](https://trello.com/c/CCelvdY0/42-foreach-lacks-browser-support)
