### ISSUE TITLE
[Question] How to clean a form inside the modal when closing

### ISSUE THREAD

**Issue by jonasmarco** [ghosh/Micromodal#393]
Hi guys,

I have a Modal and a form inside it, if the user closes the modal I would like to clean / reset the form inside Modal in the 'onClose' function, how do I do this?

**Comment by realovich** [comment]
```
onClose: modal => {
  modal.querySelector('form').reset();
},
```

**Comment by jonasmarco** [comment]
> ```
> onClose: modal => {
>   modal.querySelector('form').reset();
> },
> ```

Thank you friend. It helped me a lot.
