### ISSUE TITLE
Closing Modal on Mobile image gallery, automatically opens another modal

### ISSUE THREAD

**Issue by da-kicks-87** [ghosh/Micromodal#411]
I have made an image gallery that uses Micromodal as the popup for a larger image view.
Works fine on desktop. 

But on mobile when I close the modal from the top right "x" or bottom "close" button, it close to modal , then automatically trigger another modal from the image thumbnail that was underneath.

Anyone know why this happens only on mobile? Any fixes for this?

**Comment by ugurcanbulut** [comment]
Are you triggering the modal by using JavaScript method `MicroModal.show('modal-id')`?
If so, could you please share your code?

**Comment by da-kicks-87** [comment]
I am trigger it with **data attributes** ,  **data-micromodal-trigger="modal-1"**. With JS of **MicroModal.init();**

**Here is html code of the gallery and modal**



    <section class="bg-grey py-5 image-gallery-section">
      <div class="container">
        <div class="row">
          <div class="col-12 text-center">
            <h1 class="mb-4">Image Gallery BS Grid </h1>
            <hr class="hr-short bg-primary">
            <p>Click on images to view larger.</p>
          </div>
        </div>

        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4">

          <div class="col">
              <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1"  data-target="#carouselExampleFade" data-slide-to="0" data-aos="zoom-in" data-aos-duration="800">
                  <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-01.jpg" alt="static-image">
              </div>
          </div>

          <div class="col">
            <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary " data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="1" data-aos="zoom-in" data-aos-duration="800">
                <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-02.jpg" alt="static-image">
            </div>
          </div>

          <div class="col">
            <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="2" data-aos="zoom-in" data-aos-duration="800">
                <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-03.jpg" alt="static-image">
            </div>
          </div>

          <div class="col">
            <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary"  data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="3" data-aos="zoom-in" data-aos-duration="800">
                  <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-01.jpg" alt="static-image">
              </div>

            </div>

            <div class="col">
              <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary " data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="4" data-aos="zoom-in" data-aos-duration="800">
                <a href="#" >
                    <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-02.jpg" alt="static-image">
                    </a>
                </div>
            </div>

            <div class="col">
              <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="5" data-aos="zoom-in" data-aos-duration="800">
                    <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-03.jpg" alt="static-image">
              </div>
            </div>

            <div class="col">
                <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary " data-micromodal-trigger="modal-1"  data-target="#carouselExampleFade" data-slide-to="6" data-aos="zoom-in" data-aos-duration="800">
                      <img class="img-fluid " src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-01.jpg" alt="static-image">
                </div>
            </div>

            <div class="col">
                <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="7" data-aos="zoom-in" data-aos-duration="800">
                      <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-02.jpg" alt="static-image">
                  </div>
            </div>

            <div class="col">
              <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="8" data-aos="zoom-in" data-aos-duration="800">
                    <img class="img-fluid " src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-03.jpg" alt="static-image">
                </div>
            </div>

            <div class="col">
              <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="9" data-aos="zoom-in" data-aos-duration="800">
                    <img class="img-fluid " src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-01.jpg" alt="static-image">
              </div>
            </div>

            <div class="col">
                <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary mb-0" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="10" data-aos="zoom-in" data-aos-duration="800">
                      <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-02.jpg" alt="static-image">
                 </div>
            </div>

            <div class="col">
                <div class="img-gallery-item img-hover-zoom img-hover-zoom--basic border-secondary mb-0" data-micromodal-trigger="modal-1" data-target="#carouselExampleFade" data-slide-to="11" data-aos="zoom-in" data-aos-duration="800">
                      <img class="img-fluid" src="<?= BASEPATH ;?>src/img/gallery/thumbs/img-thumb-03.jpg" alt="static-image">
                </div>
            </div>
          </div>

        </div>

        
        <div class="modal micromodal-slide" id="modal-1" aria-hidden="true">
        <div class="modal__overlay" tabindex="-1" data-micromodal-close>
          <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
            <header class="modal__header">
              <h2 class="modal__title" id="modal-1-title">
                Micromodal
              </h2>
              <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
            </header>
            <main class="modal__content" id="modal-1-content">
              <div class="modal-body">

                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-01.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-02.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-03.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-01.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-02.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-03.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-01.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-02.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-03.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-01.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-02.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                      <img src="<?= BASEPATH ;?>src/img/gallery/large/img-03.jpg" class="d-block w-100" alt="...">
                    </div>

                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>


              </div>
            </main>
            <footer class="modal__footer">
              <button class="modal__btn modal__btn-primary">Continue</button>
              <button class="modal__btn" data-micromodal-close aria-label="Close this dialog window">Close</button>
            </footer>
          </div>
        </div>
      </div>
    </section>

**Comment by tnog** [comment]
I'm encountering a similar issue on a project, but looks like this might be a similar issue to: #324

**Comment by da-kicks-87** [comment]
@tnog Yes, the solution in that thread solved my problem. Thank you 👍
