### ISSUE TITLE
Touch scroll inside modal doesn't work

### ISSUE THREAD

**Issue by romanrei** [ghosh/micromodal#43]
How to make the touch scroll working inside modal?
Thanks :)

**Comment by casey6** [comment]
I'm having this same issue also 😞

**Comment by kalpeshsingh** [comment]
Could you please specify some technographics (Phone model, Browser etc.)? It's working as expected on Chrome (OnePlus 2).

**Comment by kalpeshsingh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Touch scroll inside modal doesn't work](https://trello.com/c/YOit1rXI/45-touch-scroll-inside-modal-doesnt-work)

**Comment by casey6** [comment]
I'm having the problem an iPhone 5s running iOS 10.2.

**Comment by kalpeshsingh** [comment]
Seems like iOS bug for scrolling `postion: fixed` element. We will look into it. Meanwhile, if you want to take stab then it would be awesome!

**Comment by PaulineNemchak** [comment]
i have the same problem in the chrome device tools

**Comment by kalpeshsingh** [comment]
Yes, @PaulineNemchak I tested that in DevTool and faced this issue. 
Hey @casey6 I think it is indeed an issue and might not related to npm.

**Comment by casey6** [comment]
Hmm, are you sure? How were you testing it? Even the version on https://micromodal.now.sh/ isn't up to date. But I believe this was fixed in #22. Pulling down the latest version of the code from this repo fixes the problem for me in devtools and on my device.

**Comment by ghosh** [comment]
Fixed in 0.2.0
