### ISSUE TITLE
First link clicked on https://micromodal.vercel.app/ on iOS opens a spammy website.

### ISSUE THREAD

**Issue by jsunsawyer** [ghosh/Micromodal#474]
I was having some issues with my modal on iOS, and wanted to test the live example from https://micromodal.vercel.app/.

Upon testing, I was immediately sent to a site called iyfnz.com. I had a friend test from a different phone and they experienced the same issue.

Just letting you know in case something is up with the security of your site.

Update: Disabling adblock on Chrome for this site resulted in the same thing on desktop.

**Comment by jsunsawyer** [comment]
Looks like https://codefund.app/ has possibly just changed hands and is utilizing existing scripts to server whatever code they want. Might want to consider removing.

**Comment by misterhamm-bzs** [comment]
Not just an iOS thing - happens on my windows desktop too

**Comment by ghosh** [comment]
Thanks for the heads up. Fixed in #479
