### ISSUE TITLE
event stop propagation on close

### ISSUE THREAD

**Issue by connorsmacartist** [ghosh/Micromodal#475]
On ios, when the close button is over another element with a touch/click event listener. Click the close button, the element behind the close element is also triggered.

**Comment by misterhamm-bzs** [comment]
+1 to this - not just an iOS issue. Looks like it might be because the modal is closing on keydown instead of keyup?

**Comment by connorsmacartist** [comment]
i actually found another thread about this and the solve is to add:

		MicroModal.show('yourmodal', {
			  onClose: function(_this, elm, e) {
					e.preventDefault();
					e.stopPropagation();
			  }			  	
		});

**Comment by misterhamm-bzs** [comment]
I found that a bit after commenting on this one. Looks like it should be in the base plugin but it's not really being maintained much anymore

**Comment by Jscherbe** [comment]
Alternatively, you could attach your own handler (addEventListener) to your close buttons (and backdrop) and then use the `MicroModal.close(id)` method to close the modal programmatically. That way you can avoid using stopPropagation, which could lead to unexpected issues (other libraries, etc).

**Comment by ghosh** [comment]
Closed by 79c75958c6aaa9cc00447b8a58ab7efbf2e84594 & #479
