### ISSUE TITLE
MicroModal not triggering modal, says Please specify at least one 'micromodal-trigger' – "data attribute."

### ISSUE THREAD

**Issue by patsch** [ghosh/Micromodal#476]
I have imported the MicroModal JS and basic CSS to an existing, older style project. The MicroModal initialisation I placed on the page...

```javascript
<script type="application/javascript">
 
    $(function() {
        MicroModal.init({
            onShow: modal => console.info(`${modal.id} is shown`), // [1]
            onClose: modal => console.info(`${modal.id} is hidden`), // [2]
            openTrigger: 'data-custom-open', // [3]
            closeTrigger: 'data-custom-close', // [4]
            openClass: 'is-open', // [5]
            disableScroll: true, // [6]
            disableFocus: false, // [7]
            awaitOpenAnimation: false, // [8]
            awaitCloseAnimation: false, // [9]
            debugMode: true // [10]
        });
        console.log('MicroModal initialised');
    });
</script>
```
...seems to work fine as I am getting the console log error:

![Screen Shot 2021-09-02 at 10 54 28 am](https://user-images.githubusercontent.com/124726/131764540-eea86f14-196f-4ed9-9add-a2482e76428a.png)

However I HAVE added such attributes, i.e. here:

```html
<span data-micromodal-trigger="modal-1" title="Click to look up the Company" id="company_lookup_link" class="cw_lookup">Lookup</span>
```

Why is the MicroModal module seemingly unable to identify the data-attribute ?

When I try to trigger the modal manually with `MicroModal.show('modal-1'); ` it works fine.

This is an older project I am extending and it's using jQuery, in case that matters.

**Comment by Jscherbe** [comment]
Not sure if you fixed this already, your configuration is saying look for an element with "data-custom-open" attribute to trigger the opening but your element is using an attribute named "data-micromodal-trigger". 

So you either need to update your span to use the attribute you specified "data-custom-open".

Or remove the setting and use whatever the default is for MicroModal (ie. "data-micromodal-trigger")

**Comment by patsch** [comment]
I ended up triggering the modals manually - but your comment makes perfect sense, I obviously didn't understand the meaning of the openTrigger and closeTrigger options. Thank you for getting back on this.
