### ISSUE TITLE
Should call preventDefault on touchstart events

### ISSUE THREAD

**Issue by markjaniczak** [ghosh/Micromodal#477]
It is not uncommon to have clickable elements underneath a modal overlay that triggers a modal close. When using the `awaitCloseAnimation` option, it is possible for a modal close element to move from under the cursor which can trigger a click on any element underneath it on mobile browsers that emulate `click` events after `touchstart` events.

This problem can be reproduced here on mobile or by using your browser's mobile emulator:

https://pt4fc.csb.app/

To prevent this, `preventDefault` should be called on the `touchstart` event in event handlers. [MDN also suggests this](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent) to prevent emulated clicks from being heard after a `touchstart` event listener has already fired.

**Comment by Jscherbe** [comment]
Is this related to [Stop Propagation on close](#475)?

**Comment by bgoewert** [comment]
> Is this related to [Stop Propagation on close](https://github.com/ghosh/Micromodal/issues/475)?
> 
> I had an issue with the close button on top of an interactive element underneath the modal, which was getting triggered by the click of the close button

It does look like https://github.com/ghosh/Micromodal/issues/475 is describing the same issue.

**Comment by ghosh** [comment]
Closed by 79c75958c6aaa9cc00447b8a58ab7efbf2e84594 & #479
