### ISSUE TITLE
Demo does not work in older browsers

### ISSUE THREAD

**Issue by rchrd2** [ghosh/micromodal#48]
Discovered this in Safari 9.1.2.

The reason is because the example code uses ES6 JavaScript template strings. 

I think (hope) the modal will work in this Safari, but the demo itself is broken.

![screen shot 2017-10-30 at 11 57 57 pm](https://user-images.githubusercontent.com/182479/32211138-6b706b34-bdce-11e7-8fe1-c3b86fdafa9c.png)

**Comment by ghosh** [comment]
@rchrd2 Thanks, we missed that. Fixed it. Can you please confirm if it's working now?
