### ISSUE TITLE
Modals closing unexpectedly with any interaction

### ISSUE THREAD

**Issue by ChrisCockram** [ghosh/Micromodal#487]
I am having an issue with the latest version of Micromodal. I currently have modals that contain forms but when any form item within the modal is interacted with inside the modal, the modal closes immediately. I don't believe this is expected behaviour, however it might just be the way I have implemented Micromodal.

[Code Pen with an example of the issue.](https://codepen.io/ChrisCockram/pen/bGryPwE)

**Comment by ghosh** [comment]
@ChrisCockram Thanks for opening this issue. Should be fixed in `0.4.8`. Feel free to open a new issue if the problem persists.

**Comment by ChrisCockram** [comment]
Cheers @ghosh, thanks for all your work on this library, It's much appreciated.

**Comment by joshangehr** [comment]
Whoa, I thought I was crazy the last hour. Thanks for opening this issue and for the quick resolution @ghosh! Can confirm that the latest version fixes this for me as well.
