### ISSUE TITLE
Remove unnecessary console logs

### ISSUE THREAD

**Issue by Log1x** [ghosh/micromodal#5]
```
MicroModal v0.1.1: ❗Please specify at least one 'micromodal-trigger' data attribute.  index.js:118
16:21:15.992 MicroModal v0.1.1: Example: <a href="#" data-micromodal-trigger="my-modal"></a>
```

I was curious if we could remove this from hitting logs every time there's a page without a modal on it?

If not, can we get a setting of some sort to set `logging` to `false`?

Thanks!

**Comment by kalpeshsingh** [comment]
Hi @Log1x ,

Thanks for raising this issue. 
I would like to know more about it. What is your case where you don't want it?

cc: @ghosh

**Comment by ghosh** [comment]
@Log1x @kalpeshsingh Thanks for bringing this up. Makes sense having a logging config. It would be useful in places where the modal markup is generated dynamically or where there is a single js file for all pages.

@kalpeshsingh Lets pick this up for our next release.

**Comment by kalpeshsingh** [comment]
Makes complete sense @ghosh 
Yep, Let's rollout in next version. 

Thank you Brandon. 
We will update you on this issue.

**Comment by ghosh** [comment]
Closed by #18

**Comment by kalpeshsingh** [comment]
Hi @Log1x ,

You might have noticed that we have added support for `debugMode`. Now, you can turn on logging by simply adding one option to `init`.

**Comment by Log1x** [comment]
Perfect. Thanks a lot guys.
