### ISSUE TITLE
Body still scrolls when disableScroll: true

### ISSUE THREAD

**Issue by nadeemja** [ghosh/micromodal#58]
Hi,

I'm doing this:

```js
MicroModal.init({disableScroll: true});
```
But, the body is still scrolling.

How to debug?

**Comment by ghosh** [comment]
@nadeemja Can you confirm if the body has the following inline styles:-

`style="overflow: initial; height: initial;"`

![screen shot 2017-12-11 at 11 44 16 am](https://user-images.githubusercontent.com/4667682/33818026-bbd4399c-de68-11e7-896d-9fa9f9f70cd4.png)

**Comment by nadeemja** [comment]
Hi! 

Thanks for replying so quickly. 

There were no such inline styles. I couldn't find anything in the docs about this? 

In any case, it works when I add this to the stylesheet: 

```css
body {
  overflow: initial; 
  height: initial;
}
```

Thank you so much for helping!
I really love your work :)

**Comment by nadeemja** [comment]
Hi,

I'm running `0.2.1`. Should I downgrade?

**Comment by ghosh** [comment]
No it should work fine. A few more questions.

- Did you install via npm or are you directly linking to the cdn?
- Which browser and version are you using?
- Are you facing this issue everywhere or is it a isolated problem?
- Can you reproduce it?

**Comment by nadeemja** [comment]
Hi,

I'm using it with Meteor via NPM. 

If I recall correctly, Meteor does some interesting things when deciding what should go into the body-tag. Might be the culprit. 

I'm using Chrome Version 62.0.3202.94 (Official Build) (64-bit).

Not sure how to answer your last two questions, as I'm just getting started using MicroModal.

**Comment by ghosh** [comment]
@nadeemja I can't reproduce this issue. Are you still having this problem?

**Comment by nadeemja** [comment]
No :)

**Comment by ghosh** [comment]
Great to hear that.
