### ISSUE TITLE
Add option for open class name

### ISSUE THREAD

**Issue by zoxon** [ghosh/Micromodal#66]
For more flexibility

**Comment by ghosh** [comment]
Thanks for the suggestion. 

We considered adding that too. However, for the sake of simplicity, we dropped that idea.

Closing this issue for now. We are open to considering it and re-opening this issue if a lot of people demand for it.

**Comment by tklives** [comment]
I would love this option as well!

Reason being, I am creating a pattern library (i.e. mini bootstrap) and would like to drive consistency on what the open/active class name is across the various components of the library.

Again though, great work with this - it is a super useful library!

Cheers,
TK
