### ISSUE TITLE
Enable animation in default config

### ISSUE THREAD

**Issue by zoxon** [ghosh/micromodal#67]
Using html and css from [gist](https://gist.github.com/ghosh/4f94cf497d7090359a5c9f81caf60699)
[Demo](https://codepen.io/Zoxon/pen/BYBXYN)

**Comment by ghosh** [comment]
Try this in the JS console
```
MicroModal.init({
  hasAnimation: true
})
```

**Comment by zoxon** [comment]
Thank you, it works. 
This is a very strange option. Usually animations are enabled by default

**Comment by ghosh** [comment]
Yes, agree with you. It feels awkward. Will change it in the next release. 

Thanks for reporting!
