### ISSUE TITLE
Cannot be used with Bootstap

### ISSUE THREAD

**Issue by serhatsnmz** [ghosh/micromodal#7]
I'm trying to use it with Bootstrap, but when I'm trying to import bootstrap.css file, it stop working.
I tried both CDN and local. Besides I've changed the order of css files in html, but nothing changed. 

> [Here is codes](https://gist.github.com/serhatsnmz/0ab47be016f4d4b9966a6408ffce029d)

**Comment by kalpeshsingh** [comment]
The `modal` class is clashing with bootstrap class. As of now, you will need to change it to something else. 

Here are three instances where you need to change it. I changed it to `micro-modal` in below snippets -

1. HTML file
`<div class="micro-modal micromodal-slide" id="modal-1" aria-hidden="true">`

2. CSS file
`.micro-modal {
  font-family: -apple-system,BlinkMacSystemFont,avenir next,avenir,helvetica neue,helvetica,ubuntu,roboto,noto,segoe ui,arial,sans-serif;
}`

3. HTML file
`.micro-modal[aria-hidden='true'] {
            display: none;
        }`

Meanwhile we will rethink on our example page classes name. Thanks for spotting this issue.

**Comment by serhatsnmz** [comment]
Everything is working good now. 
Thanks.

**Comment by ghosh** [comment]
@serhatsnmz Thanks for reporting this. 

Micromodal does not ship with any classes by default. All the styling is left up to the user to style. `modal` is just a class chosen for the example code. If you change the class name, the model will work as expected.

Closing this as it's not really a bug.

Cheers,
