### ISSUE TITLE
Callbacks not firing when modals called programmatically?

### ISSUE THREAD

**Issue by affinitycreative** [ghosh/micromodal#75]
Hello!

I noticed when using, for example, `MicroModal.show('foo'); `callbacks written for the 'onClose' or 'onShow' event in the `MicroModal.init` function, don't fire... am I missing something? 

I have tried programmatically opening a modal not seeing the `console.log` function fire, then when just clicking on the element with the 'data-micromodal-trigger' attribute it does work.

Thanks for reading and great work!

**Comment by anthonygore** [comment]
I have the same issue.

**Comment by ghosh** [comment]
@affinitycreative The `.show()` method actually instantiates a new modal. It is not meant to be used along with `.init()`

Using `.show()` enables you to open modals when you can-not/want-not to set up bindings between trigger nodes and the modal using `data-trigger`.

However, there is a way to get around this, by simulating a click on the trigger element to open the modal.
```
document.getElementById('elementID').click();
```


Hopes this clears things up.

**Comment by QJan84** [comment]
That works if a button is present, which opens the modal. If there is no button, `click()` will not work.
It would be helpful if there is a solution. I call a modal via URL parameter:

```
/* Trigger modal via URl Parameter */
let modal = UTIL.getUrlParameter(document.URL, 'modal');
if (document.getElementById(modal)) {
  MicroModal.show(modal);
}
```

**Comment by kbudasov** [comment]
Still actual issue.

**Comment by motiejunas** [comment]
So any plans for refactoring this craziness?
