### ISSUE TITLE
Getting ES module by default

### ISSUE THREAD

**Issue by anthonygore** [ghosh/micromodal#84]
I just wrestled with a bug for the last hour where I was getting non-es5 code in my Webpack bundle. Turns out I was getting the ES module version of this library when I had this in my code:

`import MicroModal from 'micromodal';`

I was able to fix it by changing to:

`import MicroModal from 'micromodal/dist/micromodal';`

Is there something wrong in the package.json or am I just doing something wrong with my webpack or babel setup maybe?

**Comment by kakadiadarpan** [comment]
Thanks for reporting this issue @anthonygore. I'll look into this

**Comment by ghosh** [comment]
@anthonygore Hey, we released a new build which should have fixed this issue. Could you please confirm if it works. `0.3.2` is the version.

Closing this for now. Please feel free to comment below incase you need to.
