### ISSUE TITLE
Double Modal

### ISSUE THREAD

**Issue by messinmotion** [ghosh/micromodal#86]
I have a case where I need to trigger a modal from inside another modal to be placed on top temporarily.

current:
#mymodal > #other-modal-trigger

but #other-modal comes to view _UNDER_ #mymodal

**Comment by messinmotion** [comment]
![](http://g.recordit.co/IH4yT1fepn.gif)

**Comment by ghosh** [comment]
Hi @messinmotion. Unfortunately, we currently do not handle this scenario yet.

Its difficult to figure out the exact problem without looking at the code. However, you could try a couple of approaches:-

-  Apply different `z-index` to the modals in css
- Try changing the order in which the modal markup is included

Closing this for now. Feel free to comment if you need to.

**Comment by messinmotion** [comment]
Thank you, I have addressed this using a data attribute to quickly add or substract z-index.
