### ISSUE TITLE
this.activeElement is null on dialog close (IE 11)

### ISSUE THREAD

**Issue by MariusBarnard** [ghosh/micromodal#87]
Opening and displaying a dialog using javascript works correctly.

Can't close the dialog due to this.activeElement being null.

This line fails, this.activeElement.focus() in the closeModel function, causing the dialog to remain open.

**Comment by kakadiadarpan** [comment]
@MariusBarnard are you closing it using `MicroModal.close('modal-id');`?

**Comment by MariusBarnard** [comment]
Dialog is shown using MicroModal.show('modal-id').

To close the dialog, using the data-micromodal-close attribute on close button on the dialog.

```html
<div class="modal micromodal-slide" id="displayOnLoad" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close="data-micromodal-close">
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="displayOnLoad-title">
      <div class="modal__header">
        <h2 class="modal__title" id="displayOnLoad-title">
          Message shown on load
        </h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close="data-micromodal-close"></button>
      </div>
      <div class="modal__content">
        <p>
          
        </p>
      </div>
      <div class="modal__footer">
        <button class="modal__btn" aria-label="Close this dialog window" data-micromodal-close="data-micromodal-close">Close</button>
      </div>
    </div>
  </div>
</div>
```


```javascript
<script type="text/javascript">
  MicroModal.show("displayOnLoad");
</script>
```

**Comment by MariusBarnard** [comment]
By changing line 137, the dialog closes in IE 11 using the close button on the dialog

```javascript
131:      key: 'closeModal',
132:      value: function closeModal() {


137:      this.activeElement.focus();
```

Add null check before calling
```javascript
if (this.activeElement) this.activeElement.focus();
```

**Comment by martinhellwagner** [comment]
Any news on putting this in the repo? Seems like a valid solution.

**Comment by erwstout** [comment]
I believe I'm having this same issue in Edge as well.

**Comment by front-stream** [comment]
Any news?

**Comment by ghosh** [comment]
Fixed in 2a78c4d095f9d5bee691054591682a02c48e1def

**Comment by dawidurbanski** [comment]
I'm using 0.4.0 (which is the newest version at the time of writing this comment), I can see code from 2a78c4d being there, but the issue persist.

IE11

If any form is added inside modal, there is no way of closing it.

`Object doesn't support property or method on 'focus'`

**Comment by matthew798** [comment]
In my case, I get the same error as above only the `activeElement` is a `SVGSVGElement`... I am on 0.4.2.
