### ISSUE TITLE
blue

### ISSUE THREAD

**Issue by diomed** [ghosh/micromodal#88]
why is there that blue mark on closing cross, after opening?
can that be removed?

**Comment by ghosh** [comment]
@diomed According to WAI ARIA practices, after opening the modal the focus should move to the first focus-able element. In this case it is the close button. The blue outline is the browser default styles for indicating the active focused element.

If you really do want to remove that, there is a configuration property called `disableFocus` you can pass when initializing the modal. To read more about see the [documentation](https://micromodal.now.sh/#configuration)
