### ISSUE TITLE
Page scroll through arrow keys

### ISSUE THREAD

**Issue by itaditya** [ghosh/micromodal#9]
When the modal is opened and the arrow keys are pressed, the page behind the overlay scrolls.
This should not be the case as currently the modal is in focus and any form of user interaction shouldn't alter the state of anything other than the modal. 
I would love to solve this issue

**Comment by csphere** [comment]
[This PR](https://github.com/ghosh/micromodal/pull/10) takes care of this, although you may want to move some things around to make the solution fit your vision for the library.

**Comment by itaditya** [comment]
The solution looks good to me.

**Comment by ghosh** [comment]
@itaditya @csphere - I am not too sure about this. The wai-aria guidelines do not mention anything about blocking scrolling when the modal is shown.

On their example page also it seems like the page behind is scrollable using the trackpad. However, using the keyboard it is not. I don't think blocking scrolling completely is a solution here.

Demo page - https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by csphere** [comment]
Only created one PR... unsure why there are 3 notifications...  In any case, [here's a PR](https://github.com/ghosh/micromodal/pull/14) with a noScroll option.

**Comment by itaditya** [comment]
Have you checked https://developers.google.com/web/updates/2017/11/overscroll-behavior#overlay .
This can be a real performance boost. I would love working on this.
